"""empty message

Revision ID: 019755086e79
Revises: 35a4961d242
Create Date: 2019-03-21 17:56:21.944148

"""

# revision identifiers, used by Alembic.
revision = '019755086e79'
down_revision = '35a4961d242'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('search_entry_links_search_id_fkey', 'search_entry_links', type_='foreignkey')
    op.drop_constraint('search_entry_links_lbc_entry_id_fkey', 'search_entry_links', type_='foreignkey')
    op.create_foreign_key(None, 'search_entry_links', 'lbc_entries', ['lbc_entry_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'search_entry_links', 'searches', ['search_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('search_user_links_user_id_fkey', 'search_user_links', type_='foreignkey')
    op.drop_constraint('search_user_links_search_id_fkey', 'search_user_links', type_='foreignkey')
    op.create_foreign_key(None, 'search_user_links', 'searches', ['search_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'search_user_links', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_user_links', type_='foreignkey')
    op.drop_constraint(None, 'search_user_links', type_='foreignkey')
    op.create_foreign_key('search_user_links_search_id_fkey', 'search_user_links', 'searches', ['search_id'], ['id'])
    op.create_foreign_key('search_user_links_user_id_fkey', 'search_user_links', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'search_entry_links', type_='foreignkey')
    op.drop_constraint(None, 'search_entry_links', type_='foreignkey')
    op.create_foreign_key('search_entry_links_lbc_entry_id_fkey', 'search_entry_links', 'lbc_entries', ['lbc_entry_id'], ['id'])
    op.create_foreign_key('search_entry_links_search_id_fkey', 'search_entry_links', 'searches', ['search_id'], ['id'])
    # ### end Alembic commands ###
