"""empty message

Revision ID: 1343b810dd6
Revises: 116e74cf415
Create Date: 2015-12-11 20:11:41.920925

"""

# revision identifiers, used by Alembic.
revision = '1343b810dd6'
down_revision = '116e74cf415'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lbc_entries', 'link_num')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lbc_entries', sa.Column('link_num', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
