"""empty message

Revision ID: 16e7885b548
Revises: 5837eb8e1bc
Create Date: 2016-10-11 15:07:46.853931

"""

# revision identifiers, used by Alembic.
revision = '16e7885b548'
down_revision = '5837eb8e1bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lbc_entries', sa.Column('imgurl', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lbc_entries', 'imgurl')
    ### end Alembic commands ###
