"""empty message

Revision ID: 1f47fba1006
Revises: 25a3261692e
Create Date: 2017-10-01 15:02:41.421926

"""

# revision identifiers, used by Alembic.
revision = '1f47fba1006'
down_revision = '25a3261692e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('vendor', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searches', 'vendor')
    ### end Alembic commands ###
