"""empty message

Revision ID: 26faff93d11
Revises: None
Create Date: 2015-12-16 12:13:34.273513

"""

# revision identifiers, used by Alembic.
revision = '26faff93d11'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lbc_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linkid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('new', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('terms', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('lbc_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lbc_entry_id'], ['lbc_entries.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.drop_table('searches')
    op.drop_table('lbc_entries')
    ### end Alembic commands ###
