"""empty message

Revision ID: 2e0f46ad6de
Revises: 2325284f388
Create Date: 2016-10-10 18:46:33.991636

"""

# revision identifiers, used by Alembic.
revision = '2e0f46ad6de'
down_revision = '2325284f388'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_user_links',
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_user_links')
    ### end Alembic commands ###
