"""empty message

Revision ID: 35a4961d242
Revises: 3eba24ccfd0
Create Date: 2017-11-14 18:24:53.579559

"""

# revision identifiers, used by Alembic.
revision = '35a4961d242'
down_revision = '3eba24ccfd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lbc_entries', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lbc_entries', 'description')
    ### end Alembic commands ###
