"""empty message

Revision ID: 3a4826b735b
Revises: 2e0f46ad6de
Create Date: 2016-10-10 19:05:05.396230

"""

# revision identifiers, used by Alembic.
revision = '3a4826b735b'
down_revision = '2e0f46ad6de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searches', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
