"""empty message

Revision ID: 3eba24ccfd0
Revises: 54f809d83fd
Create Date: 2017-10-01 20:42:26.492114

"""

# revision identifiers, used by Alembic.
revision = '3eba24ccfd0'
down_revision = '54f809d83fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('extras', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searches', 'extras')
    ### end Alembic commands ###
