"""empty message

Revision ID: 3f702735fd7
Revises: 26faff93d11
Create Date: 2015-12-16 13:03:21.493412

"""

# revision identifiers, used by Alembic.
revision = '3f702735fd7'
down_revision = '26faff93d11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('email', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searches', 'email')
    ### end Alembic commands ###
