"""empty message

Revision ID: 42f1809f9aa
Revises: 16e7885b548
Create Date: 2016-10-11 15:16:36.468949

"""

# revision identifiers, used by Alembic.
revision = '42f1809f9aa'
down_revision = '16e7885b548'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lbc_entries', sa.Column('imgnumber', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lbc_entries', 'imgnumber')
    ### end Alembic commands ###
