"""empty message

Revision ID: 565b6a3d737
Revises: 1343b810dd6
Create Date: 2015-12-12 08:40:18.424781

"""

# revision identifiers, used by Alembic.
revision = '565b6a3d737'
down_revision = '1343b810dd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('lbc_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lbc_entry_id'], ['lbc_entries.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    ### end Alembic commands ###
