"""empty message

Revision ID: 5837eb8e1bc
Revises: 3a4826b735b
Create Date: 2016-10-11 12:28:02.242758

"""

# revision identifiers, used by Alembic.
revision = '5837eb8e1bc'
down_revision = '3a4826b735b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lbc_entries', sa.Column('location', sa.String(), nullable=True))
    op.add_column('lbc_entries', sa.Column('time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lbc_entries', 'time')
    op.drop_column('lbc_entries', 'location')
    ### end Alembic commands ###
