"""empty message

Revision ID: 96c791987be3
Revises: 019755086e79
Create Date: 2019-09-29 20:52:50.210088

"""

# revision identifiers, used by Alembic.
revision = '96c791987be3'
down_revision = '019755086e79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('notify', sa.Boolean(), nullable=True))
    op.add_column('searches', sa.Column('notify_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searches', 'notify_url')
    op.drop_column('searches', 'notify')
    # ### end Alembic commands ###
