"""empty message

Revision ID: c00cf801b8
Revises: 565b6a3d737
Create Date: 2015-12-14 12:40:59.553229

"""

# revision identifiers, used by Alembic.
revision = 'c00cf801b8'
down_revision = '565b6a3d737'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lbc_entries', sa.Column('linkid', sa.Integer(), nullable=True))
    op.add_column('lbc_entries', sa.Column('new', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lbc_entries', 'new')
    op.drop_column('lbc_entries', 'linkid')
    ### end Alembic commands ###
